version: '3.8'

services:
  redis_server:
    image: "redis:latest"
    container_name: "redis_server"
    command: 
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    environment:
      - REDIS_PASSWORD=1234
      - CACHE_ENABLE=1
    ports:
      - "6379:6379"
    networks:
      - redisnet
  
networks:
  redisnet:
    driver: bridge


#redis-cli -h localhost -p 6379